Resolve footer issue
amplus-data/ckanext-amplus pull request #17
Opened 2024-11-05 16:34 UTC by teodora-aleksovska

This PR improves the footer according to the documentation. The footer background color has been changed from white to black, and a new line has been added between the body and the footer.

2024-11-06 08:15 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  height: 10px;
@teodora-aleksovska let's avoid hard-coding height. The layout is responsive and should adjust to the size of the content.

2024-11-06 08:18 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  padding: 10px 0;
@teodora-aleksovska let's use the $spacer variable, so the padding is calculated based on the Bootstrap theme spacer. We can also use the available padding classes from Bootstrap: p-1, px-1, py-5... etc. https://getbootstrap.com/docs/5.3/utilities/spacing/

2024-11-06 08:19 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  background: #070707;
@teodora-aleksovska can we use CSS variables for this, i.e. (var(--bs-color-name)? https://getbootstrap.com/docs/5.3/customize/color/

This is because we want to make the code more DRY and reusable.

2024-11-06 08:20 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  width: 100%;
@teodora-aleksovska we probably don't need a hard-coded width here.

2024-11-06 08:20 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  height: 5px;
@teodora-aleksovska Same comment as this one https://github.com/amplus-data/ckanext-amplus/pull/17/files#r1830561240.

2024-11-06 08:21 UTC, gocemitevski commented on ckanext/amplus/assets/amplus.css
> +  background-color: rgb(124, 15, 100);
@teodora-aleksovska ideally, we want to use only one type of color coding in the theme - meaning either hexadecimal, rgb, rgba... etc. We can probably use CSS variables here as well. https://getbootstrap.com/docs/5.3/customize/color/

2024-11-06 08:23 UTC, gocemitevski commented on ckanext/amplus/templates-2-10/footer.html
> +    </br></br>
@teodora-aleksovska this is not very good. We probably need to remove the <br> elements and work with margins or paddings. https://github.com/amplus-data/ckanext-amplus/pull/17/files#r1830563888

2024-11-06 08:23 UTC, gocemitevski commented on ckanext/amplus/templates/footer.html
> +    </br></br>
@teodora-aleksovska same comment as https://github.com/amplus-data/ckanext-amplus/pull/17/files#r1830570689.

2024-11-06 08:24 UTC, gocemitevski requested changes
@teodora-aleksovska please check the comments I left and refine further.

2024-11-28 12:28 UTC, teodora-aleksovska commented
This pull request has been closed and should be deleted. We will continue to commit new changes to the 'dev' branch.

2024-11-28 12:29 UTC, closed without merging